name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_library: enable
          skip_preprocessor: disable 
          enable: all
          inconclusive: enable
          inline_suppression: disable
          force: disable
          max_ctu_depth: 3
          platform: unspecified
          output_file: ./cppcheck_report.txt
          other_options: enable

      - name: Display Cppcheck Report
        run: cat ./cppcheck_report.txt

      - name: Upload Cppcheck Report
        uses: actions/upload-artifact@v2
        with:
          name: cppcheck-report
          path: ./cppcheck_report.txt
