name: cppcheck-action
on: [push]

jobs:
  build:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: cppcheck
        uses: deep5050/cppcheck-action@master # Assuming this is the correct version based on the GitHub Marketplace
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_library: enable
          skip_preprocessor: disable 
          enable: all
          inconclusive: enable
          inline_suppression: disable
          max_ctu_depth: 4
          platform: unspecified
          output_file: ./cppcheck_report.txt

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' # your branch name goes here

