name: cppcheck-action-test

on: [push]

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run cppcheck
        uses: deep5050/cppcheck-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload cppcheck report
        uses: actions/upload-artifact@v3
        with:
          name: cppcheck-report
          path: cppcheck-result.xml
